# Generated by Django 5.2.8 on 2025-12-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
