# Generated by Django 5.2.8 on 2025-12-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_match_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
