# Generated by Django 5.2.8 on 2025-12-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_match_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time_control',
            field=models.IntegerField(default=60),
        ),
    ]
