# Generated by Django 5.2.8 on 2025-12-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_match_time_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='submission',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
