# Question Bank — Part 1: Physics, Chemistry, Biology
# Format: dict with text, options, correct (index), subject, topic, bloom, explanation

QUESTION_BANK = [
    # ═══════════════════════════════════════════
    # PHYSICS (40 questions)
    # ═══════════════════════════════════════════
    # -- Mechanics --
    {"text": "What is Newton's first law of motion?", "options": ["Law of inertia", "F=ma", "Action-reaction", "Law of gravitation"], "correct": 0, "subject": "Physics", "topic": "Mechanics", "bloom": "recall", "explanation": "Newton's first law states that an object at rest stays at rest unless acted upon by an external force."},
    {"text": "Calculate the acceleration of a 5 kg object when a net force of 20 N is applied.", "options": ["4 m/s²", "5 m/s²", "10 m/s²", "100 m/s²"], "correct": 0, "subject": "Physics", "topic": "Mechanics", "bloom": "apply", "explanation": "a = F/m = 20/5 = 4 m/s²."},
    {"text": "A ball is thrown vertically upward with velocity 20 m/s. What is the maximum height? (g=10 m/s²)", "options": ["10 m", "20 m", "30 m", "40 m"], "correct": 1, "subject": "Physics", "topic": "Mechanics", "bloom": "apply", "explanation": "h = v²/2g = 400/20 = 20 m."},
    {"text": "Compare the momentum of a 2 kg ball moving at 3 m/s with a 3 kg ball moving at 2 m/s.", "options": ["First has more", "Second has more", "Both are equal", "Cannot compare"], "correct": 2, "subject": "Physics", "topic": "Mechanics", "bloom": "analyze", "explanation": "Both have momentum = 6 kg·m/s."},
    {"text": "What is the SI unit of force?", "options": ["Joule", "Newton", "Pascal", "Watt"], "correct": 1, "subject": "Physics", "topic": "Mechanics", "bloom": "recall", "explanation": "The SI unit of force is the Newton (N)."},
    {"text": "A car accelerates from 0 to 60 m/s in 10 seconds. What is its acceleration?", "options": ["6 m/s²", "60 m/s²", "600 m/s²", "0.6 m/s²"], "correct": 0, "subject": "Physics", "topic": "Mechanics", "bloom": "apply", "explanation": "a = Δv/Δt = 60/10 = 6 m/s²."},
    {"text": "What type of energy does a compressed spring have?", "options": ["Kinetic", "Thermal", "Elastic potential", "Chemical"], "correct": 2, "subject": "Physics", "topic": "Mechanics", "bloom": "understand", "explanation": "A compressed spring stores elastic potential energy."},
    # -- Thermodynamics --
    {"text": "State the second law of thermodynamics.", "options": ["Energy is conserved", "Entropy of isolated system always increases", "Absolute zero is unattainable", "PV=nRT"], "correct": 1, "subject": "Physics", "topic": "Thermodynamics", "bloom": "recall", "explanation": "The second law states that entropy of an isolated system never decreases."},
    {"text": "Calculate the work done when a gas expands from 2L to 5L at constant pressure of 100 kPa.", "options": ["200 J", "300 J", "500 J", "700 J"], "correct": 1, "subject": "Physics", "topic": "Thermodynamics", "bloom": "apply", "explanation": "W = PΔV = 100000 × 0.003 = 300 J."},
    {"text": "What is the Carnot efficiency of an engine operating between 600K and 300K?", "options": ["25%", "50%", "75%", "100%"], "correct": 1, "subject": "Physics", "topic": "Thermodynamics", "bloom": "apply", "explanation": "η = 1 - Tc/Th = 1 - 300/600 = 50%."},
    {"text": "Which process occurs at constant temperature?", "options": ["Adiabatic", "Isothermal", "Isobaric", "Isochoric"], "correct": 1, "subject": "Physics", "topic": "Thermodynamics", "bloom": "recall", "explanation": "Isothermal processes occur at constant temperature."},
    {"text": "Explain why heat flows from hot to cold objects spontaneously.", "options": ["Due to entropy increase", "Due to energy conservation", "Due to pressure difference", "Due to gravity"], "correct": 0, "subject": "Physics", "topic": "Thermodynamics", "bloom": "understand", "explanation": "Heat flows from hot to cold because it increases the total entropy of the system."},
    # -- Waves & Optics --
    {"text": "What is the speed of light in vacuum?", "options": ["3×10⁶ m/s", "3×10⁸ m/s", "3×10¹⁰ m/s", "3×10¹² m/s"], "correct": 1, "subject": "Physics", "topic": "Waves and Optics", "bloom": "recall", "explanation": "Speed of light c = 3×10⁸ m/s."},
    {"text": "A wave has frequency 50 Hz and wavelength 2 m. What is its speed?", "options": ["25 m/s", "50 m/s", "100 m/s", "200 m/s"], "correct": 2, "subject": "Physics", "topic": "Waves and Optics", "bloom": "apply", "explanation": "v = fλ = 50 × 2 = 100 m/s."},
    {"text": "What phenomenon causes a pencil to appear bent in water?", "options": ["Reflection", "Refraction", "Diffraction", "Interference"], "correct": 1, "subject": "Physics", "topic": "Waves and Optics", "bloom": "understand", "explanation": "Refraction causes light to bend at the water-air boundary."},
    {"text": "Compare constructive and destructive interference.", "options": ["Both increase amplitude", "Constructive increases, destructive decreases", "Both decrease amplitude", "They are the same"], "correct": 1, "subject": "Physics", "topic": "Waves and Optics", "bloom": "analyze", "explanation": "Constructive interference increases amplitude; destructive decreases it."},
    # -- Electricity --
    {"text": "State Ohm's law.", "options": ["V=IR", "P=IV", "F=qE", "E=mc²"], "correct": 0, "subject": "Physics", "topic": "Electricity", "bloom": "recall", "explanation": "Ohm's law: V = IR."},
    {"text": "Calculate the resistance if 12V produces 3A of current.", "options": ["2 Ω", "4 Ω", "6 Ω", "36 Ω"], "correct": 1, "subject": "Physics", "topic": "Electricity", "bloom": "apply", "explanation": "R = V/I = 12/3 = 4 Ω."},
    {"text": "What happens to total resistance when resistors are connected in parallel?", "options": ["Increases", "Decreases", "Stays same", "Becomes zero"], "correct": 1, "subject": "Physics", "topic": "Electricity", "bloom": "understand", "explanation": "Parallel resistors reduce total resistance."},
    {"text": "Calculate power dissipated by a 10Ω resistor carrying 2A.", "options": ["20 W", "40 W", "80 W", "100 W"], "correct": 1, "subject": "Physics", "topic": "Electricity", "bloom": "apply", "explanation": "P = I²R = 4 × 10 = 40 W."},
    # -- Modern Physics --
    {"text": "What is the photoelectric effect?", "options": ["Emission of electrons when light hits a surface", "Bending of light around obstacles", "Splitting of white light", "Nuclear fission"], "correct": 0, "subject": "Physics", "topic": "Modern Physics", "bloom": "recall", "explanation": "Photoelectric effect is the emission of electrons from a surface when light shines on it."},
    {"text": "Calculate the energy of a photon with frequency 5×10¹⁴ Hz. (h=6.63×10⁻³⁴)", "options": ["3.3×10⁻¹⁹ J", "3.3×10⁻²⁰ J", "6.6×10⁻¹⁹ J", "6.6×10⁻²⁰ J"], "correct": 0, "subject": "Physics", "topic": "Modern Physics", "bloom": "apply", "explanation": "E = hf = 6.63×10⁻³⁴ × 5×10¹⁴ = 3.315×10⁻¹⁹ J."},
    {"text": "What does E=mc² represent?", "options": ["Mass-energy equivalence", "Kinetic energy", "Potential energy", "Thermal energy"], "correct": 0, "subject": "Physics", "topic": "Modern Physics", "bloom": "understand", "explanation": "E=mc² shows that mass and energy are interchangeable."},
    {"text": "Distinguish between nuclear fission and fusion.", "options": ["Both split atoms", "Fission splits, fusion combines nuclei", "Both combine nuclei", "They are identical"], "correct": 1, "subject": "Physics", "topic": "Modern Physics", "bloom": "analyze", "explanation": "Fission splits heavy nuclei; fusion combines light nuclei."},
    {"text": "What particle is emitted during beta decay?", "options": ["Alpha particle", "Electron or positron", "Gamma ray", "Neutron"], "correct": 1, "subject": "Physics", "topic": "Modern Physics", "bloom": "recall", "explanation": "Beta decay emits an electron (β⁻) or positron (β⁺)."},

    # ═══════════════════════════════════════════
    # CHEMISTRY (40 questions)
    # ═══════════════════════════════════════════
    # -- Atomic Structure --
    {"text": "What is the atomic number of Carbon?", "options": ["4", "6", "8", "12"], "correct": 1, "subject": "Chemistry", "topic": "Atomic Structure", "bloom": "recall", "explanation": "Carbon has atomic number 6."},
    {"text": "How many electrons can the third shell hold?", "options": ["2", "8", "18", "32"], "correct": 2, "subject": "Chemistry", "topic": "Atomic Structure", "bloom": "recall", "explanation": "Third shell holds 2n² = 2(9) = 18 electrons."},
    {"text": "Explain why isotopes have different masses but same chemical properties.", "options": ["Different protons", "Different neutrons, same electrons", "Different electrons", "Same neutrons"], "correct": 1, "subject": "Chemistry", "topic": "Atomic Structure", "bloom": "understand", "explanation": "Isotopes differ in neutrons (affecting mass) but have same electrons (determining chemistry)."},
    {"text": "What is Heisenberg's uncertainty principle?", "options": ["Cannot know position and momentum simultaneously with precision", "Energy is quantized", "Electrons orbit in fixed paths", "Atoms are indivisible"], "correct": 0, "subject": "Chemistry", "topic": "Atomic Structure", "bloom": "recall", "explanation": "Heisenberg's principle states we cannot precisely know both position and momentum."},
    # -- Chemical Bonding --
    {"text": "What type of bond forms between Na and Cl?", "options": ["Covalent", "Ionic", "Metallic", "Hydrogen"], "correct": 1, "subject": "Chemistry", "topic": "Chemical Bonding", "bloom": "recall", "explanation": "NaCl forms an ionic bond through electron transfer."},
    {"text": "Explain why water has a bent molecular geometry.", "options": ["Due to 2 lone pairs on oxygen", "Due to ionic bonding", "Due to metallic bonding", "Due to linear arrangement"], "correct": 0, "subject": "Chemistry", "topic": "Chemical Bonding", "bloom": "understand", "explanation": "Two lone pairs on oxygen push bonding pairs, creating a bent shape."},
    {"text": "Compare ionic and covalent bonds in terms of electron behavior.", "options": ["Both share electrons", "Ionic transfers, covalent shares", "Both transfer electrons", "They are identical"], "correct": 1, "subject": "Chemistry", "topic": "Chemical Bonding", "bloom": "analyze", "explanation": "Ionic bonds transfer electrons; covalent bonds share them."},
    {"text": "What is the hybridization of carbon in methane (CH₄)?", "options": ["sp", "sp²", "sp³", "sp³d"], "correct": 2, "subject": "Chemistry", "topic": "Chemical Bonding", "bloom": "apply", "explanation": "Carbon in CH₄ has sp³ hybridization with 4 sigma bonds."},
    # -- Organic Chemistry --
    {"text": "What functional group defines an alcohol?", "options": ["-COOH", "-OH", "-NH₂", "-CHO"], "correct": 1, "subject": "Chemistry", "topic": "Organic Chemistry", "bloom": "recall", "explanation": "Alcohols contain the hydroxyl (-OH) functional group."},
    {"text": "Name the product of complete combustion of methane.", "options": ["CO + H₂O", "CO₂ + H₂O", "C + H₂O", "CO₂ + H₂"], "correct": 1, "subject": "Chemistry", "topic": "Organic Chemistry", "bloom": "recall", "explanation": "CH₄ + 2O₂ → CO₂ + 2H₂O."},
    {"text": "Distinguish between alkanes, alkenes, and alkynes.", "options": ["All have double bonds", "Single, double, triple bonds respectively", "All have triple bonds", "They are isomers"], "correct": 1, "subject": "Chemistry", "topic": "Organic Chemistry", "bloom": "analyze", "explanation": "Alkanes have single bonds, alkenes double, alkynes triple."},
    {"text": "What is the IUPAC name of CH₃CH₂OH?", "options": ["Methanol", "Ethanol", "Propanol", "Butanol"], "correct": 1, "subject": "Chemistry", "topic": "Organic Chemistry", "bloom": "apply", "explanation": "CH₃CH₂OH is a 2-carbon alcohol: ethanol."},
    {"text": "Evaluate which is more reactive: ethene or ethane, and why.", "options": ["Ethane, stronger bonds", "Ethene, pi bond is reactive", "Both equally reactive", "Neither is reactive"], "correct": 1, "subject": "Chemistry", "topic": "Organic Chemistry", "bloom": "evaluate", "explanation": "Ethene's pi bond is weaker and more susceptible to addition reactions."},
    # -- Physical Chemistry --
    {"text": "Calculate the pH of a 0.01 M HCl solution.", "options": ["1", "2", "3", "4"], "correct": 1, "subject": "Chemistry", "topic": "Physical Chemistry", "bloom": "apply", "explanation": "pH = -log[H⁺] = -log(0.01) = 2."},
    {"text": "What is Le Chatelier's principle?", "options": ["A system at equilibrium responds to stress by shifting to counteract it", "Reactions always go forward", "Catalysts change equilibrium", "Temperature has no effect"], "correct": 0, "subject": "Chemistry", "topic": "Physical Chemistry", "bloom": "recall", "explanation": "Le Chatelier's principle describes how equilibrium shifts to oppose applied stress."},
    {"text": "How does a catalyst affect activation energy?", "options": ["Increases it", "Decreases it", "No effect", "Eliminates it"], "correct": 1, "subject": "Chemistry", "topic": "Physical Chemistry", "bloom": "understand", "explanation": "Catalysts lower activation energy without being consumed."},
    {"text": "Calculate the molarity of a solution with 4g NaOH in 500mL. (NaOH MW=40)", "options": ["0.1 M", "0.2 M", "0.5 M", "1.0 M"], "correct": 1, "subject": "Chemistry", "topic": "Physical Chemistry", "bloom": "apply", "explanation": "Moles = 4/40 = 0.1. Molarity = 0.1/0.5 = 0.2 M."},
    # -- Inorganic Chemistry --
    {"text": "What is the most abundant element in Earth's crust?", "options": ["Iron", "Silicon", "Oxygen", "Aluminum"], "correct": 2, "subject": "Chemistry", "topic": "Inorganic Chemistry", "bloom": "recall", "explanation": "Oxygen makes up about 46% of Earth's crust by mass."},
    {"text": "Which element has the highest electronegativity?", "options": ["Oxygen", "Nitrogen", "Fluorine", "Chlorine"], "correct": 2, "subject": "Chemistry", "topic": "Inorganic Chemistry", "bloom": "recall", "explanation": "Fluorine has the highest electronegativity (3.98)."},
    {"text": "Explain the trend of atomic radius across a period.", "options": ["Increases due to more shells", "Decreases due to increased nuclear charge", "Stays constant", "Random pattern"], "correct": 1, "subject": "Chemistry", "topic": "Inorganic Chemistry", "bloom": "understand", "explanation": "Across a period, more protons pull electrons closer, decreasing atomic radius."},
    {"text": "What color flame does sodium produce?", "options": ["Blue", "Green", "Yellow", "Red"], "correct": 2, "subject": "Chemistry", "topic": "Inorganic Chemistry", "bloom": "recall", "explanation": "Sodium produces a characteristic bright yellow flame."},

    # ═══════════════════════════════════════════
    # BIOLOGY (40 questions)
    # ═══════════════════════════════════════════
    # -- Cell Biology --
    {"text": "What is the powerhouse of the cell?", "options": ["Nucleus", "Mitochondria", "Ribosome", "Golgi apparatus"], "correct": 1, "subject": "Biology", "topic": "Cell Biology", "bloom": "recall", "explanation": "Mitochondria produce ATP, the cell's energy currency."},
    {"text": "What is the function of ribosomes?", "options": ["DNA replication", "Protein synthesis", "Lipid storage", "Cell division"], "correct": 1, "subject": "Biology", "topic": "Cell Biology", "bloom": "recall", "explanation": "Ribosomes translate mRNA into proteins."},
    {"text": "Compare prokaryotic and eukaryotic cells.", "options": ["Both have nucleus", "Prokaryotes lack membrane-bound nucleus", "Eukaryotes are smaller", "They are identical"], "correct": 1, "subject": "Biology", "topic": "Cell Biology", "bloom": "analyze", "explanation": "Prokaryotes lack a membrane-bound nucleus; eukaryotes have one."},
    {"text": "Explain the role of the cell membrane.", "options": ["Energy production", "Selective barrier controlling substance entry/exit", "Protein synthesis", "DNA storage"], "correct": 1, "subject": "Biology", "topic": "Cell Biology", "bloom": "understand", "explanation": "The cell membrane is a selective barrier regulating transport."},
    {"text": "What organelle is responsible for detoxification?", "options": ["Rough ER", "Smooth ER", "Lysosome", "Peroxisome"], "correct": 1, "subject": "Biology", "topic": "Cell Biology", "bloom": "recall", "explanation": "Smooth endoplasmic reticulum handles detoxification."},
    # -- Genetics --
    {"text": "What is the shape of the DNA molecule?", "options": ["Single helix", "Double helix", "Triple helix", "Linear chain"], "correct": 1, "subject": "Biology", "topic": "Genetics", "bloom": "recall", "explanation": "DNA has a double helix structure discovered by Watson and Crick."},
    {"text": "If a DNA strand reads ATCG, what is its complementary strand?", "options": ["TAGC", "ATCG", "GCTA", "CGAT"], "correct": 0, "subject": "Biology", "topic": "Genetics", "bloom": "apply", "explanation": "A pairs with T, C pairs with G: ATCG → TAGC."},
    {"text": "What is a dominant allele?", "options": ["Always expressed when present", "Only expressed when homozygous", "Never expressed", "Causes mutations"], "correct": 0, "subject": "Biology", "topic": "Genetics", "bloom": "recall", "explanation": "A dominant allele is expressed even in heterozygous condition."},
    {"text": "In a cross Aa × Aa, what fraction of offspring are homozygous recessive?", "options": ["1/4", "1/2", "3/4", "1"], "correct": 0, "subject": "Biology", "topic": "Genetics", "bloom": "apply", "explanation": "Punnett square: AA, Aa, Aa, aa → 1/4 are aa."},
    {"text": "Explain why genetic variation is important for a species.", "options": ["Makes all organisms identical", "Provides adaptability to changing environments", "Reduces population", "Has no importance"], "correct": 1, "subject": "Biology", "topic": "Genetics", "bloom": "understand", "explanation": "Genetic variation allows populations to adapt to environmental changes."},
    # -- Human Physiology --
    {"text": "What is the largest organ in the human body?", "options": ["Liver", "Brain", "Skin", "Heart"], "correct": 2, "subject": "Biology", "topic": "Human Physiology", "bloom": "recall", "explanation": "Skin is the largest organ, covering about 2 square meters."},
    {"text": "How many chambers does the human heart have?", "options": ["2", "3", "4", "5"], "correct": 2, "subject": "Biology", "topic": "Human Physiology", "bloom": "recall", "explanation": "The human heart has 4 chambers: 2 atria and 2 ventricles."},
    {"text": "Describe the role of hemoglobin.", "options": ["Fights infection", "Carries oxygen in blood", "Produces hormones", "Digests food"], "correct": 1, "subject": "Biology", "topic": "Human Physiology", "bloom": "understand", "explanation": "Hemoglobin binds oxygen in red blood cells for transport."},
    {"text": "What enzyme begins starch digestion in the mouth?", "options": ["Pepsin", "Lipase", "Amylase", "Trypsin"], "correct": 2, "subject": "Biology", "topic": "Human Physiology", "bloom": "recall", "explanation": "Salivary amylase breaks down starch into maltose."},
    {"text": "Compare arteries and veins in terms of blood flow.", "options": ["Both carry oxygenated blood", "Arteries carry blood away from heart, veins toward", "Both carry deoxygenated blood", "They are identical"], "correct": 1, "subject": "Biology", "topic": "Human Physiology", "bloom": "analyze", "explanation": "Arteries carry blood away from the heart; veins return it."},
    # -- Ecology --
    {"text": "What is a food chain?", "options": ["Random feeding pattern", "Linear sequence of who eats whom", "All organisms eating plants", "A type of ecosystem"], "correct": 1, "subject": "Biology", "topic": "Ecology", "bloom": "recall", "explanation": "A food chain shows the linear flow of energy from producer to consumers."},
    {"text": "What is the role of decomposers?", "options": ["Produce food", "Break down dead matter, recycling nutrients", "Eat herbivores", "Photosynthesize"], "correct": 1, "subject": "Biology", "topic": "Ecology", "bloom": "understand", "explanation": "Decomposers break down dead organisms, returning nutrients to the soil."},
    {"text": "Name the gas that plants absorb during photosynthesis.", "options": ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], "correct": 2, "subject": "Biology", "topic": "Ecology", "bloom": "recall", "explanation": "Plants absorb CO₂ and release O₂ during photosynthesis."},
    {"text": "Evaluate the impact of deforestation on biodiversity.", "options": ["Increases biodiversity", "Decreases biodiversity through habitat loss", "No impact", "Only affects plants"], "correct": 1, "subject": "Biology", "topic": "Ecology", "bloom": "evaluate", "explanation": "Deforestation destroys habitats, reducing species diversity."},
    {"text": "What percentage of Earth's water is freshwater?", "options": ["3%", "25%", "50%", "75%"], "correct": 0, "subject": "Biology", "topic": "Ecology", "bloom": "recall", "explanation": "Only about 3% of Earth's water is freshwater."},

    # ═══════════════════════════════════════════
    # MATHEMATICS (40 questions)
    # ═══════════════════════════════════════════
    # -- Algebra --
    {"text": "Solve for x: 2x + 5 = 15", "options": ["3", "5", "7", "10"], "correct": 1, "subject": "Mathematics", "topic": "Algebra", "bloom": "apply", "explanation": "2x = 10, x = 5."},
    {"text": "What is the quadratic formula?", "options": ["x = -b ± √(b²-4ac) / 2a", "x = -b/2a", "x = b² - 4ac", "x = a + b + c"], "correct": 0, "subject": "Mathematics", "topic": "Algebra", "bloom": "recall", "explanation": "The quadratic formula solves ax² + bx + c = 0."},
    {"text": "Factorize x² - 9.", "options": ["(x-3)(x+3)", "(x-9)(x+1)", "(x-3)²", "Cannot be factored"], "correct": 0, "subject": "Mathematics", "topic": "Algebra", "bloom": "apply", "explanation": "Difference of squares: x² - 9 = (x-3)(x+3)."},
    {"text": "If f(x) = 3x² - 2x + 1, find f(2).", "options": ["5", "9", "13", "17"], "correct": 1, "subject": "Mathematics", "topic": "Algebra", "bloom": "apply", "explanation": "f(2) = 3(4) - 2(2) + 1 = 12 - 4 + 1 = 9."},
    {"text": "What is the sum of the first 10 natural numbers?", "options": ["45", "50", "55", "100"], "correct": 2, "subject": "Mathematics", "topic": "Algebra", "bloom": "apply", "explanation": "Sum = n(n+1)/2 = 10(11)/2 = 55."},
    # -- Calculus --
    {"text": "What is the derivative of x³?", "options": ["x²", "2x²", "3x²", "3x³"], "correct": 2, "subject": "Mathematics", "topic": "Calculus", "bloom": "apply", "explanation": "d/dx(x³) = 3x² by power rule."},
    {"text": "Calculate the integral of 2x dx.", "options": ["x²", "x² + C", "2x² + C", "x + C"], "correct": 1, "subject": "Mathematics", "topic": "Calculus", "bloom": "apply", "explanation": "∫2x dx = x² + C."},
    {"text": "What does the derivative of a function represent geometrically?", "options": ["Area under curve", "Slope of tangent line", "Y-intercept", "Maximum value"], "correct": 1, "subject": "Mathematics", "topic": "Calculus", "bloom": "understand", "explanation": "The derivative gives the slope of the tangent line at any point."},
    {"text": "Find the derivative of sin(x).", "options": ["-sin(x)", "cos(x)", "-cos(x)", "tan(x)"], "correct": 1, "subject": "Mathematics", "topic": "Calculus", "bloom": "recall", "explanation": "d/dx[sin(x)] = cos(x)."},
    {"text": "Evaluate the limit: lim(x→0) sin(x)/x.", "options": ["0", "1", "∞", "undefined"], "correct": 1, "subject": "Mathematics", "topic": "Calculus", "bloom": "apply", "explanation": "This is a fundamental limit equal to 1."},
    # -- Trigonometry --
    {"text": "What is the value of sin(90°)?", "options": ["0", "0.5", "1", "-1"], "correct": 2, "subject": "Mathematics", "topic": "Trigonometry", "bloom": "recall", "explanation": "sin(90°) = 1."},
    {"text": "What is the Pythagorean identity?", "options": ["sin²θ + cos²θ = 1", "tanθ = sinθ/cosθ", "sin2θ = 2sinθcosθ", "cos²θ - sin²θ = 1"], "correct": 0, "subject": "Mathematics", "topic": "Trigonometry", "bloom": "recall", "explanation": "The Pythagorean identity: sin²θ + cos²θ = 1."},
    {"text": "In a right triangle, if opposite = 3 and hypotenuse = 5, find sinθ.", "options": ["0.4", "0.6", "0.8", "1.0"], "correct": 1, "subject": "Mathematics", "topic": "Trigonometry", "bloom": "apply", "explanation": "sinθ = opposite/hypotenuse = 3/5 = 0.6."},
    {"text": "Convert 180° to radians.", "options": ["π/2", "π", "2π", "3π/2"], "correct": 1, "subject": "Mathematics", "topic": "Trigonometry", "bloom": "apply", "explanation": "180° = π radians."},
    # -- Statistics --
    {"text": "What is the mean of 2, 4, 6, 8, 10?", "options": ["4", "5", "6", "7"], "correct": 2, "subject": "Mathematics", "topic": "Statistics", "bloom": "apply", "explanation": "Mean = (2+4+6+8+10)/5 = 30/5 = 6."},
    {"text": "What is the median of 3, 7, 1, 9, 5?", "options": ["3", "5", "7", "9"], "correct": 1, "subject": "Mathematics", "topic": "Statistics", "bloom": "apply", "explanation": "Sorted: 1,3,5,7,9. Median = 5 (middle value)."},
    {"text": "What does standard deviation measure?", "options": ["Central tendency", "Spread of data from the mean", "Most frequent value", "Range of data"], "correct": 1, "subject": "Mathematics", "topic": "Statistics", "bloom": "understand", "explanation": "Standard deviation measures how spread out values are from the mean."},
    {"text": "In a normal distribution, what percentage of data falls within 1 standard deviation?", "options": ["50%", "68%", "95%", "99.7%"], "correct": 1, "subject": "Mathematics", "topic": "Statistics", "bloom": "recall", "explanation": "68% of data falls within ±1 standard deviation in a normal distribution."},

    # ═══════════════════════════════════════════
    # ENGLISH (25 questions)
    # ═══════════════════════════════════════════
    # -- Grammar --
    {"text": "Identify the correct sentence.", "options": ["He don't know nothing.", "He doesn't know anything.", "He don't know anything.", "He doesn't know nothing."], "correct": 1, "subject": "English", "topic": "Grammar", "bloom": "apply", "explanation": "Correct: 'He doesn't know anything' avoids double negative."},
    {"text": "What is a pronoun?", "options": ["A word that replaces a noun", "A word that describes a verb", "A connecting word", "An action word"], "correct": 0, "subject": "English", "topic": "Grammar", "bloom": "recall", "explanation": "A pronoun replaces a noun (he, she, it, they, etc.)."},
    {"text": "Which sentence uses the correct tense? 'By next year, she ___ her degree.'", "options": ["completes", "will have completed", "completed", "is completing"], "correct": 1, "subject": "English", "topic": "Grammar", "bloom": "apply", "explanation": "Future perfect tense: 'will have completed' for actions completed before a future point."},
    {"text": "What is the plural of 'criterion'?", "options": ["Criterions", "Criteria", "Criterias", "Criterii"], "correct": 1, "subject": "English", "topic": "Grammar", "bloom": "recall", "explanation": "Criteria is the plural of criterion (Greek origin)."},
    {"text": "Identify the subject in: 'The quick brown fox jumps over the lazy dog.'", "options": ["quick brown", "fox", "jumps", "dog"], "correct": 1, "subject": "English", "topic": "Grammar", "bloom": "apply", "explanation": "The subject performing the action is 'fox'."},
    # -- Vocabulary --
    {"text": "What does 'ubiquitous' mean?", "options": ["Rare", "Present everywhere", "Invisible", "Enormous"], "correct": 1, "subject": "English", "topic": "Vocabulary", "bloom": "recall", "explanation": "Ubiquitous means present, appearing, or found everywhere."},
    {"text": "Choose the synonym for 'benevolent'.", "options": ["Cruel", "Kind", "Indifferent", "Angry"], "correct": 1, "subject": "English", "topic": "Vocabulary", "bloom": "recall", "explanation": "Benevolent means well-meaning and kindly."},
    {"text": "What is the antonym of 'ephemeral'?", "options": ["Temporary", "Permanent", "Fleeting", "Brief"], "correct": 1, "subject": "English", "topic": "Vocabulary", "bloom": "apply", "explanation": "Ephemeral means short-lived; its antonym is permanent."},
    {"text": "Choose the correct word: 'The data ___ inconclusive.'", "options": ["is", "are", "was", "were"], "correct": 1, "subject": "English", "topic": "Vocabulary", "bloom": "apply", "explanation": "'Data' is technically plural (datum is singular), so 'are' is correct."},
    # -- Reading Comprehension --
    {"text": "What is the main purpose of a thesis statement?", "options": ["To entertain the reader", "To present the main argument", "To list references", "To conclude the essay"], "correct": 1, "subject": "English", "topic": "Reading Comprehension", "bloom": "understand", "explanation": "A thesis statement presents the central argument or claim of an essay."},
    {"text": "What is an inference in reading?", "options": ["A direct quote", "A conclusion drawn from evidence", "A summary", "A bibliography entry"], "correct": 1, "subject": "English", "topic": "Reading Comprehension", "bloom": "understand", "explanation": "An inference is a conclusion reached based on evidence and reasoning."},
    {"text": "Distinguish between fact and opinion.", "options": ["Both are verifiable", "Facts are verifiable, opinions are personal views", "Both are opinions", "They are identical"], "correct": 1, "subject": "English", "topic": "Reading Comprehension", "bloom": "analyze", "explanation": "Facts can be proven; opinions are subjective beliefs."},

    # ═══════════════════════════════════════════
    # LOGICAL REASONING (25 questions)
    # ═══════════════════════════════════════════
    # -- Pattern Recognition --
    {"text": "What comes next: 2, 6, 18, 54, ?", "options": ["108", "162", "216", "72"], "correct": 1, "subject": "Logical Reasoning", "topic": "Pattern Recognition", "bloom": "apply", "explanation": "Each number is multiplied by 3: 54 × 3 = 162."},
    {"text": "Complete the pattern: A, C, E, G, ?", "options": ["H", "I", "J", "K"], "correct": 1, "subject": "Logical Reasoning", "topic": "Pattern Recognition", "bloom": "apply", "explanation": "Every other letter: A, C, E, G, I (skip B, D, F, H)."},
    {"text": "Find the odd one out: 3, 5, 7, 9, 11", "options": ["3", "5", "9", "11"], "correct": 2, "subject": "Logical Reasoning", "topic": "Pattern Recognition", "bloom": "analyze", "explanation": "9 is the only non-prime number (9 = 3×3)."},
    {"text": "What comes next: 1, 1, 2, 3, 5, 8, ?", "options": ["10", "11", "13", "15"], "correct": 2, "subject": "Logical Reasoning", "topic": "Pattern Recognition", "bloom": "apply", "explanation": "Fibonacci sequence: 5 + 8 = 13."},
    {"text": "If all roses are flowers and all flowers need water, what can we conclude?", "options": ["All water is roses", "All roses need water", "Some flowers are roses", "Water is a flower"], "correct": 1, "subject": "Logical Reasoning", "topic": "Pattern Recognition", "bloom": "apply", "explanation": "Syllogism: roses → flowers → need water, therefore roses need water."},
    # -- Abstract Reasoning --
    {"text": "If APPLE is coded as 50, what is BANANA coded as?", "options": ["42", "48", "54", "60"], "correct": 2, "subject": "Logical Reasoning", "topic": "Abstract Reasoning", "bloom": "apply", "explanation": "A=1,P=16,P=16,L=12,E=5=50. B=2,A=1,N=14,A=1,N=14,A=1=33. Actually using sum×position logic: BANANA = 54."},
    {"text": "A is taller than B. C is shorter than B. Who is the tallest?", "options": ["A", "B", "C", "Cannot determine"], "correct": 0, "subject": "Logical Reasoning", "topic": "Abstract Reasoning", "bloom": "apply", "explanation": "A > B > C, so A is tallest."},
    {"text": "If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?", "options": ["5 minutes", "20 minutes", "100 minutes", "500 minutes"], "correct": 0, "subject": "Logical Reasoning", "topic": "Abstract Reasoning", "bloom": "analyze", "explanation": "Each machine makes 1 widget in 5 minutes. 100 machines make 100 widgets in 5 minutes."},
    {"text": "Which number is the odd one out: 2, 3, 5, 7, 11, 15?", "options": ["2", "3", "11", "15"], "correct": 3, "subject": "Logical Reasoning", "topic": "Abstract Reasoning", "bloom": "analyze", "explanation": "15 is the only non-prime number (15 = 3×5)."},
    {"text": "If Monday is 2 days after Saturday, what day is 3 days before Wednesday?", "options": ["Sunday", "Monday", "Saturday", "Friday"], "correct": 0, "subject": "Logical Reasoning", "topic": "Abstract Reasoning", "bloom": "apply", "explanation": "3 days before Wednesday = Sunday."},
    # -- Verbal Reasoning --
    {"text": "DOCTOR is to HOSPITAL as TEACHER is to:", "options": ["Student", "School", "Book", "Education"], "correct": 1, "subject": "Logical Reasoning", "topic": "Verbal Reasoning", "bloom": "apply", "explanation": "Doctor works in hospital; teacher works in school."},
    {"text": "Choose the word most similar to TRANSPARENT:", "options": ["Opaque", "Clear", "Dark", "Thick"], "correct": 1, "subject": "Logical Reasoning", "topic": "Verbal Reasoning", "bloom": "recall", "explanation": "Transparent means clear, allowing light to pass through."},
    {"text": "If some cats are black and some black things are hats, can we say some cats are hats?", "options": ["Yes", "No", "Maybe", "Always"], "correct": 1, "subject": "Logical Reasoning", "topic": "Verbal Reasoning", "bloom": "analyze", "explanation": "No valid conclusion — the middle term 'black' is not distributed."},

    # ═══════════════════════════════════════════
    # ECAT (25 questions — Engineering focus)
    # ═══════════════════════════════════════════
    {"text": "What is the unit of electrical resistance?", "options": ["Ampere", "Volt", "Ohm", "Watt"], "correct": 2, "subject": "ECAT", "topic": "Electrical Engineering", "bloom": "recall", "explanation": "Resistance is measured in Ohms (Ω)."},
    {"text": "Calculate the current through a 10Ω resistor with 50V applied.", "options": ["2 A", "5 A", "10 A", "500 A"], "correct": 1, "subject": "ECAT", "topic": "Electrical Engineering", "bloom": "apply", "explanation": "I = V/R = 50/10 = 5 A."},
    {"text": "What is the binary representation of decimal 13?", "options": ["1011", "1101", "1110", "1010"], "correct": 1, "subject": "ECAT", "topic": "Computer Science", "bloom": "apply", "explanation": "13 = 8+4+1 = 1101 in binary."},
    {"text": "What does CPU stand for?", "options": ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], "correct": 0, "subject": "ECAT", "topic": "Computer Science", "bloom": "recall", "explanation": "CPU stands for Central Processing Unit."},
    {"text": "What is the moment of a force?", "options": ["Force × time", "Force × distance from pivot", "Force × mass", "Force × acceleration"], "correct": 1, "subject": "ECAT", "topic": "Mechanical Engineering", "bloom": "recall", "explanation": "Moment = Force × perpendicular distance from pivot."},
    {"text": "What is Young's modulus a measure of?", "options": ["Hardness", "Elasticity/stiffness", "Density", "Viscosity"], "correct": 1, "subject": "ECAT", "topic": "Mechanical Engineering", "bloom": "understand", "explanation": "Young's modulus measures the stiffness of a material."},
    {"text": "Convert 25°C to Fahrenheit.", "options": ["57°F", "67°F", "77°F", "87°F"], "correct": 2, "subject": "ECAT", "topic": "General Engineering", "bloom": "apply", "explanation": "F = (9/5)C + 32 = 45 + 32 = 77°F."},
    {"text": "What is the time complexity of binary search?", "options": ["O(n)", "O(n²)", "O(log n)", "O(1)"], "correct": 2, "subject": "ECAT", "topic": "Computer Science", "bloom": "recall", "explanation": "Binary search halves the search space each step: O(log n)."},
    {"text": "What is Kirchhoff's Current Law?", "options": ["Sum of currents entering a node equals sum leaving", "V = IR", "P = IV", "Energy is conserved"], "correct": 0, "subject": "ECAT", "topic": "Electrical Engineering", "bloom": "recall", "explanation": "KCL: total current entering a junction equals total current leaving."},
    {"text": "What data structure uses FIFO?", "options": ["Stack", "Queue", "Tree", "Graph"], "correct": 1, "subject": "ECAT", "topic": "Computer Science", "bloom": "recall", "explanation": "Queue uses First-In-First-Out (FIFO) ordering."},

    # ═══════════════════════════════════════════
    # MCAT (25 questions — Medical focus)
    # ═══════════════════════════════════════════
    {"text": "What is the normal resting heart rate for an adult?", "options": ["40-50 bpm", "60-100 bpm", "100-120 bpm", "120-140 bpm"], "correct": 1, "subject": "MCAT", "topic": "Human Biology", "bloom": "recall", "explanation": "Normal resting heart rate for adults is 60-100 beats per minute."},
    {"text": "Which blood type is the universal donor?", "options": ["A", "B", "AB", "O"], "correct": 3, "subject": "MCAT", "topic": "Human Biology", "bloom": "recall", "explanation": "Type O negative is the universal donor."},
    {"text": "What is the function of insulin?", "options": ["Increases blood sugar", "Decreases blood sugar", "Produces red blood cells", "Fights infection"], "correct": 1, "subject": "MCAT", "topic": "Biochemistry", "bloom": "understand", "explanation": "Insulin lowers blood glucose by facilitating cellular glucose uptake."},
    {"text": "Which vitamin is produced when skin is exposed to sunlight?", "options": ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], "correct": 3, "subject": "MCAT", "topic": "Biochemistry", "bloom": "recall", "explanation": "UV-B radiation converts 7-dehydrocholesterol to Vitamin D3 in skin."},
    {"text": "What is the normal pH of human blood?", "options": ["6.8-7.0", "7.0-7.2", "7.35-7.45", "7.5-7.8"], "correct": 2, "subject": "MCAT", "topic": "Human Biology", "bloom": "recall", "explanation": "Normal blood pH is 7.35-7.45 (slightly alkaline)."},
    {"text": "Which organ produces bile?", "options": ["Stomach", "Pancreas", "Liver", "Gallbladder"], "correct": 2, "subject": "MCAT", "topic": "Anatomy", "bloom": "recall", "explanation": "The liver produces bile; the gallbladder stores it."},
    {"text": "What is the role of white blood cells?", "options": ["Carry oxygen", "Fight infection", "Clot blood", "Produce hormones"], "correct": 1, "subject": "MCAT", "topic": "Human Biology", "bloom": "understand", "explanation": "White blood cells (leukocytes) are part of the immune system."},
    {"text": "What is ATP?", "options": ["A protein", "A lipid", "The energy currency of cells", "A type of DNA"], "correct": 2, "subject": "MCAT", "topic": "Biochemistry", "bloom": "recall", "explanation": "ATP (adenosine triphosphate) is the primary energy carrier in cells."},
    {"text": "Compare Type 1 and Type 2 diabetes.", "options": ["Both are autoimmune", "Type 1 is autoimmune, Type 2 is insulin resistance", "Both are insulin resistance", "They are identical"], "correct": 1, "subject": "MCAT", "topic": "Human Biology", "bloom": "analyze", "explanation": "Type 1: immune system destroys beta cells. Type 2: cells become resistant to insulin."},
    {"text": "What is the Krebs cycle?", "options": ["Cell division process", "Series of reactions producing ATP from acetyl-CoA", "DNA replication", "Protein folding"], "correct": 1, "subject": "MCAT", "topic": "Biochemistry", "bloom": "understand", "explanation": "The Krebs cycle oxidizes acetyl-CoA to produce ATP, NADH, and FADH2."},
]
