# Generated by Django 5.2.12 on 2026-03-26 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matchmaking", "0005_matchplayer_submission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The question text")),
                (
                    "options",
                    models.JSONField(
                        help_text='List of answer options, e.g. ["opt1", "opt2", "opt3", "opt4"]'
                    ),
                ),
                (
                    "correct_answer_index",
                    models.IntegerField(
                        help_text="0-based index of the correct answer in options list"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Explanation for the correct answer",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Physics", "Physics"),
                            ("Chemistry", "Chemistry"),
                            ("Biology", "Biology"),
                            ("Mathematics", "Mathematics"),
                            ("English", "English"),
                            ("Logical Reasoning", "Logical Reasoning"),
                            ("ECAT", "ECAT"),
                            ("MCAT", "MCAT"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        db_index=True,
                        help_text="Specific topic within the subject",
                        max_length=100,
                    ),
                ),
                (
                    "difficulty_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Auto-calculated difficulty: 0.0 = Very Easy, 1.0 = Very Hard",
                    ),
                ),
                (
                    "text_complexity",
                    models.FloatField(
                        default=0.5,
                        help_text="Flesch-Kincaid based text complexity score",
                    ),
                ),
                (
                    "bloom_level",
                    models.CharField(
                        choices=[
                            ("recall", "Recall"),
                            ("understand", "Understand"),
                            ("apply", "Apply"),
                            ("analyze", "Analyze"),
                            ("evaluate", "Evaluate"),
                        ],
                        default="recall",
                        help_text="Bloom's Taxonomy cognitive level",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["subject", "topic", "difficulty_score"],
                "indexes": [
                    models.Index(
                        fields=["subject", "difficulty_score"],
                        name="ml_engine_q_subject_d2602b_idx",
                    ),
                    models.Index(
                        fields=["topic", "difficulty_score"],
                        name="ml_engine_q_topic_d03a3f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_strengths",
                    models.JSONField(
                        default=dict,
                        help_text='Per-subject accuracy, e.g. {"Physics": 0.85, "Biology": 0.42}',
                    ),
                ),
                (
                    "topic_strengths",
                    models.JSONField(
                        default=dict,
                        help_text='Per-topic accuracy, e.g. {"Mechanics": 0.90, "Optics": 0.35}',
                    ),
                ),
                (
                    "avg_time_per_question",
                    models.FloatField(
                        default=30.0,
                        help_text="Average seconds per question across all attempts",
                    ),
                ),
                ("total_questions_attempted", models.IntegerField(default=0)),
                (
                    "accuracy_rate",
                    models.FloatField(
                        default=0.0, help_text="Overall accuracy (0.0 to 1.0)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student profiles",
            },
        ),
        migrations.CreateModel(
            name="CheatingFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("time_anomaly", "Time Anomaly"),
                            ("score_spike", "Score Spike"),
                            ("answer_pattern", "Answer Pattern"),
                            ("composite", "Composite (Multiple Signals)"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.FloatField(
                        help_text="Cheating probability score: 0.0 = unlikely, 1.0 = almost certain"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        help_text="Detailed breakdown of anomaly scores and evidence"
                    ),
                ),
                (
                    "reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether an admin has reviewed this flag",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheating_flags",
                        to="matchmaking.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheating_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "flag_type"],
                        name="ml_engine_c_user_id_279d95_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="ml_engine_c_severit_2a453a_idx"
                    ),
                    models.Index(
                        fields=["reviewed"], name="ml_engine_c_reviewe_c1d4d9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QuestionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_answer",
                    models.CharField(
                        help_text="The answer the student selected", max_length=500
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="Whether the selected answer was correct"
                    ),
                ),
                (
                    "time_taken_seconds",
                    models.FloatField(
                        help_text="Time in seconds to answer this question"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_attempts",
                        to="matchmaking.match",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="ml_engine.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "question"],
                        name="ml_engine_q_student_07c3b6_idx",
                    ),
                    models.Index(
                        fields=["student", "is_correct"],
                        name="ml_engine_q_student_d19f62_idx",
                    ),
                    models.Index(
                        fields=["question", "is_correct"],
                        name="ml_engine_q_questio_fcaf5f_idx",
                    ),
                ],
            },
        ),
    ]
